### PR TITLE
Add copy explaining requirements

### PR DESCRIPTION
**Pull request by caffo**
Explain that a phoenix based blog is required for proper
tutorial execution.

wlbtfzl1

### CODE REVIEW

**Comment by bruce** [comment]
Maybe just say "Phoenix application," since "phoenix blog" is somewhat vague.

@benwilson512 What "prerequisites" do you see as needing to be posted here?

**Comment by benwilson512** [comment]
We should link to http://www.phoenixframework.org/docs/up-and-running probably instead of the main site. That's the only real prerequisite because the actual data retrieval is explicitly stubbed. if we re-wrote the tutorial to be more concrete we'd need to worry about postgres and such.

**Comment by caffo** [comment]
Updated.

**Comment by bruce** [comment]
Looks good. I'll merge and deploy.

**Pull request merged**
